name: pr-insight

on: workflow_dispatch
#   pull_request:
#   issue_comment:
jobs:
  pr_assistant_job:
    runs-on: ubuntu-latest
    name: Run pr insight on every pull request, respond to user comments
    steps:
      - name: PR Insight action step
        id: prassistant
        uses: khulnasoft/pr-insight@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          OPENAI_ORG: ${{ secrets.OPENAI_ORG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
